services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf
      - .:/var/www/html
    depends_on:
      - mysql
      - php-fpm
      - php-daemon
    links:
      - mysql
      - php-fpm
      - php-daemon
    labels:
      - "traefik.http.routers.wpoker.rule=Host(`wpoker.local`)"
    networks:
      - traefik
      - default

  php-fpm:
    build:
      context: ./docker
      dockerfile: php.local.dockerfile
    ports:
      - "5173:5173"
    volumes:
      - .:/var/www/html

  mysql:
    image: percona:5.7.26
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=wpoker
      - MYSQL_USER=wpoker
      - MYSQL_PASSWORD=wpoker
    ports:
      - "8006:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  php-daemon:
    build:
      context: ./docker
      dockerfile: php.cli.dockerfile
    ports:
      - "${APP_SOCKET_PORT:-3000}:${APP_SOCKET_PORT:-3000}"
    command: php /app/artisan workman start
    links:
      - mysql
    volumes:
      - .:/app

volumes:
  mysql-data:

networks:
  traefik:
    external: true